#LINK https://amao12580.github.io/post/2016/04/Nginx-with-docker-part-one/

#说明：因为我所在的网络环境非常差，所以将很多需要下载的Step单独用RUN定义了，以免每次网络连不上而重复下载。如果你的网络环境OK，可以考虑合并多个RUN,以进一步减少imags的大小
#定义基础镜像
FROM alpine:latest
LABEL maintainer="clhey@cokapp.com"
#定义nginx版本
ENV NGINX_VERSION 1.12.2
#将安装源切换为国内环境(中国科学技术大学)，大大加快了安装速度，同时稳定性也有了保障
ENV MIRROR_URL http://mirrors.ustc.edu.cn/alpine/
ENV MIRROR_URL_BACKUP http://alpine.gliderlabs.com/alpine/
ENV MIRROR_URL_SLOWEST http://dl-cdn.alpinelinux.org/alpine/
#准备安装环境
RUN echo '' > /etc/apk/repositories && \
    echo "${MIRROR_URL}v3.3//main"     >> /etc/apk/repositories && \
    echo "${MIRROR_URL}v3.3//community" >> /etc/apk/repositories
#安装必要的组件(如果发生  ERROR: Service 'nginx' failed to build: The command '/bin/sh -c apk add... returned a non-zero code: 12。  这是网络问题：请删干净未完成container和images，10分钟后再来一遍)
RUN apk add --no-cache --virtual .build-deps \
    gcc \
    libc-dev \
    make \
    openssl-dev \
    pcre-dev \
    zlib-dev \
    linux-headers \
    curl \
    jemalloc-dev \
    gd-dev \
    git
#下载安装包和补丁
RUN mkdir -p /var/run/nginx/
RUN wget -c http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
#进行编译安装，同时打上补丁
RUN tar -xzvf nginx-${NGINX_VERSION}.tar.gz && \
cd nginx-${NGINX_VERSION} && \
#去除nginx的对外版本号
sed -i -e 's/${NGINX_VERSION}//g' -e 's/nginx\//ERROR/g' -e 's/"NGINX"/"ERROR"/g' src/core/nginx.h  && \
./configure --prefix=/usr/local/nginx \
--with-pcre \
--with-ipv6 \
--with-http_ssl_module \
--with-http_flv_module \
--with-http_v2_module \
--with-http_realip_module \
--with-http_gzip_static_module \
--with-http_stub_status_module \
--with-http_mp4_module \
--with-http_image_filter_module \
--with-http_addition_module \
--with-http_sub_module  \
--with-http_dav_module  \
--with-stream \
--with-stream_ssl_module \
--http-client-body-temp-path=/usr/local/nginx/client/ \
--http-proxy-temp-path=/usr/local/nginx/proxy/ \
--http-fastcgi-temp-path=/usr/local/nginx/fcgi/ \
--http-uwsgi-temp-path=/usr/local/nginx/uwsgi \
--http-scgi-temp-path=/usr/local/nginx/scgi \
--with-ld-opt="-ljemalloc" && \
#开始编译
make -j $(awk '/processor/{i++}END{print i}' /proc/cpuinfo) && make install && \
#设置一些工作目录
mkdir -p /usr/local/nginx/cache/ && \
mkdir -p /usr/local/nginx/temp/ && \
rm -rf ../{ngx*,nginx*}


COPY nginx.conf /usr/local/nginx/nginx.conf
RUN rm -rf /usr/local/nginx/conf.d/*
COPY ./conf.d /usr/local/nginx/conf.d
COPY ./_ssl /usr/local/nginx/_ssl

VOLUME ["/usr/local/nginx/conf.d"]

EXPOSE 80 443


CMD ["./usr/local/nginx/sbin/nginx", "-g", "daemon off;"]















# FROM nginx:1.12
# MAINTAINER clhey@cokapp.com

# # copy app
# COPY nginx.conf /etc/nginx/nginx.conf
# RUN rm -rf /etc/nginx/conf.d/*
# COPY ./conf.d /etc/nginx/conf.d
# COPY ./_ssl /etc/nginx/_ssl

# VOLUME ["/etc/nginx/conf.d"]

# EXPOSE 80 443