version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - /home/zheteng-data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: hcl850924
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: hcl850924
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8608:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: hcl850924